// <auto-generated />
namespace Cusat_University.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InstructorAndOffceAdeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstructorAndOffceAdeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201903212115343_InstructorAndOffceAdeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
